### ISSUE TITLE
Foundry VTT Version 11 Support

### ISSUE THREAD

**Issue by WesWedding** [BoltsJ/lancer-initiative#37]
**Is your feature request related to a problem? Please describe.**
The module is not usable in Version 11 of Foundry VTT.

**Describe the solution you'd like**
Version 11 support.

**Describe alternatives you've considered**
I simply updated the supported versions in the manifest and it seemed like the module still worked pretty good!  I am not very experienced with Foundry nor this module, though, so my word should be taken with a grain of salt.  I'm trying to use a module that depends on this one.

**Comment by akselander** [comment]
I forked the repo and created PR that bumps maximum version. I also created a release so there's a download link for people who didn't download Lancer Initiative on v10. I haven't done any changes except for the version bump, so things might change!

https://github.com/akselander/lancer-initiative/releases/latest/download/module.json

**Comment by BoltsJ** [comment]
This is partially done and you can install on foundry 11, but the configuration menu styling is messed up and the secret disposition isn't handled.

Also, if you installed the fork that @akselander made, you'll need to uninstall and reinstall because the manifest included in that release is malformed and breaks the foundry updater.

**Comment by akselander** [comment]
Thanks for fixing, I deliberately disconnected my fork from this one, but perhaps I could have named it differently so it's more clear.
